name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
  deploy:
    name: Deploy
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          directory: functions
          envkey_TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
          envkey_TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          envkey_REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          envkey_ORG_NAME: ${{ github.ORG_NAME }}
      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=default --only functions,firestore -f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
